export const skills: Skill[] = [
  {
    name: "JavaScript",
    level: 5,
    icon: "javascript",
    experience: "6 yrs",
    years: "Jan 2021 – Present",
    description: "The main language I used professionally",
  },
  {
    name: "TypeScript",
    level: 5,
    icon: "typescript",
    experience: "6 yrs",
    years: "Jan 2021 – Present",
    description: "Where I use Javascript, Typescript has always been in it's shadow.",
  },
  {
    name: "SvelteKit",
    level: 5,
    icon: "svelte",
    experience: "3 yrs",
    years: "Mar 2024 – Present",
    description: "Experienced in building applications with SvelteKit.",
  },
  {
    name: "Node.js",
    level: 5,
    icon: "nodejs",
    experience: "6 yrs",
    years: "Jan 2021 – Present",
    description: "The entire backend of my 2nd job (2024-2026) has been built using Node.js.",
  },
  {
    name: "Express.js",
    level: 4,
    icon: "expressjs",
    experience: "4 yrs",
    years: "2019 – Present",
    description: "Experienced in building RESTful APIs with Express.js.",
  },
  {
    name: "MongoDB",
    level: 3,
    icon: "mongodb",
    experience: "3 yrs",
    years: "2020 – Present",
    description: "Familiar with MongoDB for NoSQL database management.",
  },
  {
    name: "Mongoose",
    level: 3,
    icon: "mongoose",
    experience: "3 yrs",
    years: "2020 – Present",
    description: "Familiar with Mongoose for MongoDB object modeling.",
  },
  {
    name: "Tailwind CSS",
    level: 4,
    icon: "tailwind-css",
    experience: "3 yrs",
    years: "2020 – Present",
    description: "Proficient in using Tailwind CSS for styling.",
  },
  {
    name: "Git",
    level: 4,
    icon: "git",
    experience: "5 yrs",
    years: "2018 – Present",
    description: "Experienced in version control with Git.",
  },
  {
    name: "GitHub",
    level: 5,
    icon: "github",
    experience: "9 yrs",
    years: "2018 – Present",
    description: "I have been the go-to guy in every role I filled, when things break, and commits disappear.",
  },
  {
    name: "The Language: C",
    level: 3,
    icon: "c",
    experience: "3 yrs",
    years: "2020 – Present",
    description: "Familiar with C programming for system-level development.",
  },
  {
    name: "Java",
    level: 3,
    icon: "java",
    experience: "3 yrs",
    years: "2020 – Present",
    description: "Experienced in Java for object-oriented programming.",
  },
  {
    name: "Docker",
    level: 3,
    icon: "docker",
    experience: "3 yrs",
    years: "2020 – Present",
    description: "Familiar with containerization using Docker.",
  },
  {
    name: "Firebase",
    level: 3,
    icon: "firebase",
    experience: "3 yrs",
    years: "2020 – Present",
    description: "Experienced in using Firebase for backend services.",
  },
  {
    name: "CapacitorJS",
    level: 4,
    icon: "capacitorjs",
    experience: "3 yrs",
    years: "2024 – Present",
    description: "Experienced in building cross-platform mobile apps with Capacitor.",
  },
  {
    name: "Flutter",
    level: 2,
    icon: "flutter",
    experience: "few mos.",
    years: "2024",
    description: "Familiar with Flutter for cross-platform mobile app development.",
  },
  {
    name: "Storybook",
    level: 3,
    icon: "storybook",
    experience: "3 yrs",
    years: "2020 – Present",
    description: "Familiar with Storybook for UI component development.",
  },
  {
    name: "Vue.js",
    level: 3,
    icon: "vuejs",
    experience: "3 yrs",
    years: "2020 – Present",
    description: "Familiar with Vue.js for building user interfaces.",
  },
  {
    name: "Bash",
    level: 3,
    icon: "bash",
    experience: "3 yrs",
    years: "2020 – Present",
    description: "Familiar with Bash for scripting and automation.",
  }
];

export const projects: Project[] = [
  {
    title: "Doenit",
    description: "An Afrikaans ToDo list app built to be simple, private, and offline-first.",
    image_src: "/doenit-logo.webp",
    tech: ["SvelteKit", "Capacitor", "Firebase"],
    status: "in_development",
    href: "/doenit",
  },
  {
    title: "Vinkel Of Koljander",
    description: "A website I created for my family to share recipes",
    image_src: "/vinkel-of-koljander-logo.webp",
    tech: ["SvelteKit", "Firebase"],
    status: "improving",
    href: "/vinkel-of-koljander",
  },
  {
    title: "My Wedding website",
    description:
      "A website I built for my wedding for guests to RSVP, find basic information and handle the gift registry.",
    image_src: "/trou-webwerf-logo.webp",
    tech: ["Vue.js"],
    status: "production",
  },
  {
    title: "Tradesmith",
    description: "A project to automatically trade cryptocurrency based on a set of rules and strategies.",
    image_src: "/tradesmith-logo.png",
    tech: ["Vue.js", "Binance API", "Luno API"],
    status: "shelved",
  },
  {
    title: "Console Colours",
    description: "A small library to add colour to console output in Node.js.",
    tech: ["Node.js", "Typescript"],
    status: "shelved",
  },
  {
    title: "Woorde Wenk",
    description: "A simple word game built for Afrikaans learners to practice their vocabulary.",
    tech: ["Firebase", "WhatsApp API"],
    status: "shelved",
  },
];
