export const skills: Skill[] = [
  {
    name: "JavaScript",
    level: 5,
    icon: "/icons/javascript.webp",
    experience: "5 yrs",
    years: "2018 – Present",
    description: "Proficient in JavaScript for web development.",
  },
  {
    name: "TypeScript",
    level: 5,
    icon: "/icons/typescript.webp",
    experience: "4 yrs",
    years: "2019 – Present",
    description: "Strong understanding of TypeScript for type-safe development.",
  },
  {
    name: "SvelteKit",
    level: 5,
    icon: "/icons/sveltekit.webp",
    experience: "3 yrs",
    years: "2020 – Present",
    description: "Experienced in building applications with SvelteKit.",
  },
  {
    name: "Node.js",
    level: 5,
    icon: "/icons/nodejs.webp",
    experience: "5 yrs",
    years: "2018 – Present",
    description: "Skilled in server-side development with Node.js.",
  },
  {
    name: "Express.js",
    level: 4,
    icon: "/icons/express.webp",
    experience: "4 yrs",
    years: "2019 – Present",
    description: "Experienced in building RESTful APIs with Express.js.",
  },
  {
    name: "MongoDB",
    level: 3,
    icon: "/icons/mongodb.webp",
    experience: "3 yrs",
    years: "2020 – Present",
    description: "Familiar with MongoDB for NoSQL database management.",
  },
  {
    name: "Tailwind CSS",
    level: 4,
    icon: "/icons/tailwind.webp",
    experience: "3 yrs",
    years: "2020 – Present",
    description: "Proficient in using Tailwind CSS for styling.",
  },
  {
    name: "Git",
    level: 4,
    icon: "/icons/git.webp",
    experience: "5 yrs",
    years: "2018 – Present",
    description: "Experienced in version control with Git.",
  },
  {
    name: "GitHub",
    level: 5,
    icon: "/icons/github.webp",
    experience: "5 yrs",
    years: "2018 – Present",
    description: "Proficient in using GitHub for collaboration and code hosting.",
  },
  {
    name: "C",
    level: 3,
    icon: "/icons/c.webp",
    experience: "3 yrs",
    years: "2020 – Present",
    description: "Familiar with C programming for system-level development.",
  },
  {
    name: "Java",
    level: 3,
    icon: "/icons/java.webp",
    experience: "3 yrs",
    years: "2020 – Present",
    description: "Experienced in Java for object-oriented programming.",
  },
  {
    name: "Docker",
    level: 3,
    icon: "/icons/docker.webp",
    experience: "3 yrs",
    years: "2020 – Present",
    description: "Familiar with containerization using Docker.",
  },
  {
    name: "Firebase",
    level: 3,
    icon: "/icons/firebase.webp",
    experience: "3 yrs",
    years: "2020 – Present",
    description: "Experienced in using Firebase for backend services.",
  },
];

export const projects: Project[] = [
  {
    title: "Doenit",
    description: "An Afrikaans ToDo list app built to be simple, private, and offline-first.",
    image_src: "/doenit-logo.webp",
    tech: ["SvelteKit", "Capacitor", "Firebase"],
    status: "in_development",
    href: "/doenit",
  },
  {
    title: "Vinkel Of Koljander",
    description: "A website I created for my family to share recipes",
    image_src: "/vinkel-of-koljander-logo.webp",
    tech: ["SvelteKit", "Firebase"],
    status: "improving",
    href: "/vinkel-of-koljander",
  },
  {
    title: "My Wedding website",
    description:
      "A website I built for my wedding for guests to RSVP, find basic information and handle the gift registry.",
    image_src: "/trou-webwerf-logo.webp",
    tech: ["Vue.js"],
    status: "production",
  },
  {
    title: "Tradesmith",
    description: "A project to automatically trade cryptocurrency based on a set of rules and strategies.",
    image_src: "/tradesmith-logo.png",
    tech: ["Vue.js", "Binance API", "Luno API"],
    status: "shelved",
  },
  {
    title: "Console Colours",
    description: "A small library to add colour to console output in Node.js.",
    tech: ["Node.js", "Typescript"],
    status: "shelved",
  },
  {
    title: "Woorde Wenk",
    description: "A simple word game built for Afrikaans learners to practice their vocabulary.",
    tech: ["Firebase", "WhatsApp API"],
    status: "shelved",
  },
];
