import { page } from "$app/state";

export default function t(key: keyof (typeof map)["en"]): string {
  const lang: "en" | "af" = page.data.lang || "en";
  return map[lang]?.[key] || map["en"]?.[key] || key;
}

const map = {
  en: {
    intro_sentence:
      "I'm a Software Developer who has been building software since 2021, primarily in start-up environments. Outside of work, I build my own projects to sharpen my skills, explore new ideas, and keep learning.",
    skills: "Skills",
    my_projects: "My Projects",
    skill_javascript_desc: "The main language I use professionally.",
    skill_typescript_desc: "Where I use JavaScript, TypeScript has always been in its shadow.",
    skill_sveltekit_desc: "The main frontend framework I use professionally.",
    skill_nodejs_desc: "The entire backend of UNAFFI has been built using Node.js.",
    skill_expressjs_desc: "Exposed all our RESTful APIs using Express.js at UNAFFI.",
    skill_mongodb_desc: "The main database software I used at UNAFFI.",
    skill_mongoose_desc: "Modelled UNAFFI's data using Mongoose.",
    skill_tailwind_desc: "All my SvelteKit projects are styled using Tailwind CSS.",
    skill_git_desc: "I have been using Git for version control in all my projects.",
    skill_github_desc: "I have been the go-to guy in every role I filled, when things break, or commits disappear.",
    skill_c_desc: "One of the 2 main languages used at my 3 years at University – and my personal favourite.",
    skill_java_desc: "One of the 2 main languages used at my 3 years at University.",
    skill_docker_desc: "Familiar with containerization using Docker.",
    skill_firebase_desc: "My personal projects often utilise Firebase for its database or push notification service.",
    skill_capacitorjs_desc: "I have published 2 cross-platform mobile apps using Capacitor.",
    skill_flutter_desc: "I have been looking at flutter, but have very limited experience with it.",
    skill_storybook_desc: "At UNAFFI we used Storybook for developing and testing UI components in isolation.",
    skill_vuejs_desc: "I built two personal projects using Vue.js.",
    skill_bash_desc: "At UNAFFI I wrote many automation scripts for redundant server tasks.",
    skill_journeyapps_desc: "The platform used to develop and deploy custom business applications quickly and efficiently at Gatekeeper.",
    skill_react_desc: "Only light dabbling, but seems easy enough.",
    nav_full_stack_dev: "Full-Stack Software Developer",
    nav_luxembourg_bound: "Luxembourg Bound • From South Africa",
    nav_available_text:
      "Available & actively seeking full-time developer opportunities in the Luxembourg or German tech industry.",
    nav_more_about_me: "More about me",
    nav_read_more: "Read more detailed",
    nav_home: "Home",
    nav_my_projects_short: "My Projects",
    search_skills: "Search skills...",
    project_status_in_development: "In Development",
    project_status_shelved: "Shelved",
    project_status_production: "Production",
    project_status_improving: "Improving",
    project_title_doenit: "Doenit",
    project_desc_doenit: "An Afrikaans ToDo list app built to be simple, private, and offline-first.",
    project_title_vinkel_of_koljander: "Vinkel Of Koljander",
    project_desc_vinkel_of_koljander: "A website I created for my family to share recipes",
    project_title_wedding_website: "My Wedding website",
    project_desc_wedding_website:
      "A website I built for my wedding for guests to RSVP, find basic information and handle the gift registry.",
    project_title_tradesmith: "Tradesmith",
    project_desc_tradesmith: "A project to automatically trade cryptocurrency based on a set of rules and strategies.",
    project_title_console_colours: "Console Colours",
    project_desc_console_colours: "A small library to add colour to console output in Node.js.",
    project_title_woorde_wenk: "Woorde Wenk",
    project_desc_woorde_wenk: "A simple word game built for Afrikaans learners to practice their vocabulary.",
    project_title_this_website: "This Website",
    project_desc_this_website: "My personal website to introduce myself",
    about_introduction: "Introduction",
    about_summary: "Summary",
    about_languages: "Languages",
    about_english: "English",
    about_english_level: "Fluent",
    about_afrikaans: "Afrikaans",
    about_afrikaans_level: "Fluent",
    about_german: "German",
    about_german_level: "Elementary (A2)",
    about_date_of_birth: "Date of birth",
    about_location: "Location",
    about_south_africa: "South Africa",
    about_south_africa_label: "My Current Residence",
    about_luxembourg: "Luxembourg",
    about_luxembourg_label: "Looking for opportunities in Luxembourg",
    about_availability: "Availability",
    about_references: "References",
    about_available_upon_request: "Available upon request",
    about_hobbies: "Hobbies",
    about_reading: "Reading",
    about_reading_desc: "Personal development and fiction",
    about_coding: "Coding",
    about_coding_desc: "Building projects and exploring new ideas",
    about_exploring: "Exploring",
    about_exploring_desc: "Nature, places, and fresh perspectives",
    about_jogging: "Jogging",
    about_jogging_desc: "Completed 2 marathons",
    about_education: "Education",
    about_university: "University",
    about_university_desc:
      "I completed my undergraduate/bachelor's studies in 2020 at the University of Stellenbosch. I majored in Mathematics and Computer Science.",
    about_high_school: "High School",
    about_high_school_desc: "I finished my metric in 2016 in South Africa, Cape Town.",
    about_other_education: "Other Education",
    about_other_education_p1:
      "I attended a leadership and adventure program in my gap-year throughout 2017.",
    about_other_education_p2:
      "I also worked through various Udemy courses. Most of my learning in the last few years comes from my personal projects and self-study.",
    about_work_experience: "Work Experience",
    about_unaffi: "UNAFFI",
    about_unaffi_li_1:
      "Led frontend architecture decisions, including data modelling, API design, folder structure, and code organization standards.",
    about_unaffi_li_2:
      "Executed all code reviews across the team and used ESLint standards and best practices.",
    about_unaffi_li_3: "Developed applications with JavaScript, SvelteKit, Express, Zod, and OpenAPI.",
    about_unaffi_li_4:
      "Integrated authentication systems with Ory and built mobile apps (for Web, Android, and iOS) using SvelteKit and CapacitorJS.",
    about_unaffi_li_5: "Created automation scripts to streamline server operations and deployment workflows.",
    about_unaffi_li_6: "Collaborated with a 4-person technical team on feature development and delivery.",
    about_gatekeeper: "Gatekeeper Technologies",
    about_gatekeeper_li_1:
      "Led a small team to create 2 new applications and maintain 6 existing applications, most notably for the Western Cape Traffic Department.",
    about_gatekeeper_li_2:
      "Owned the full project lifecycle, from client requirements and solution design to implementation, delivery, and support.",
    about_gatekeeper_li_3:
      "Built client-facing applications using the JourneyApps platform, which uses XML, JavaScript, and TypeScript.",
    about_gatekeeper_li_4: "Published multiple private npm packages for internal company use.",
    about_gatekeeper_li_5: "Trained all team members as the company grew from 3 to 10 developers.",
  },
  af: {
    intro_sentence:
      "Ek is ’n Software Developer met ervaring in startups sedert 2021. Buite werk bou ek aan my eie projekte om my vaardighede te slyp, met nuwe idees te eksperimenteer en aan te hou leer.",
    skills: "Vaardighede",
    my_projects: "My Projekte",
    skill_javascript_desc: "Die hooftaal wat ek professioneel gebruik.",
    skill_typescript_desc: "Waar ek JavaScript gebruik, was TypeScript altyd in sy skaduwee.",
    skill_sveltekit_desc: "Die hoof frontend-raamwerk wat ek professioneel gebruik.",
    skill_nodejs_desc: "Die hele backend van UNAFFI is met Node.js gebou.",
    skill_expressjs_desc: "Ons REST API's is by UNAFFI met Express.js blootgestel.",
    skill_mongodb_desc: "Die hoofdatabasis sagteware wat ek by UNAFFI gebruik het.",
    skill_mongoose_desc: "UNAFFI se data is met Mongoose gemodelleer.",
    skill_tailwind_desc: "Al my SvelteKit-projekte word met Tailwind CSS gestyl.",
    skill_git_desc: "Ek gebruik Git vir weergawebeheer in al my projekte.",
    skill_github_desc: "Ek was die persoon wat altyd gehelp het wanneer dinge breek of committs verdwyn.",
    skill_c_desc: "Een van die 2 hooftale wat ek oor my 3 jaar aan die universiteit gebruik het – en my gunsteling.",
    skill_java_desc: "Een van die 2 hooftale wat ek oor my 3 jaar aan die universiteit gebruik het.",
    skill_docker_desc: "Bekend met containerisering met Docker.",
    skill_firebase_desc: "My persoonlike projekte gebruik gereeld Firebase vir die databasis of push-notifikasiediens.",
    skill_capacitorjs_desc: "Ek het 2 kruisplatform mobiele toepassings met Capacitor gepubliseer.",
    skill_flutter_desc: "Ek het beperkte ervaring met Flutter.",
    skill_storybook_desc: "By UNAFFI het ons Storybook gebruik om UI-komponente in isolasie te ontwikkel en te toets.",
    skill_vuejs_desc: "Ek het twee persoonlike projekte met Vue.js gebou.",
    skill_bash_desc: "By UNAFFI het ek baie outomatiseringsskripte vir herhalende bedienerwerk geskryf.",
    skill_journeyapps_desc: "Die platform wat gebruik is om pasgemaakte besigheidsprogramme vinnig en doeltreffend te ontwikkel en te ontplooi by Gatekeeper.",
    skill_react_desc: "Slegs ligte eksperimentering, maar dit lyk redelik maklik.",
    nav_full_stack_dev: "Vol-stapel Sagteware-ontwikkelaar",
    nav_luxembourg_bound: "Oppad na Luxemburg • Van Suid-Afrika",
    nav_available_text:
      "Beskikbaar en aktief op soek na voltydse ontwikkelaargeleenthede in die Luxemburgse of Duitse tegnologiebedryf.",
    nav_more_about_me: "Meer oor my",
    nav_read_more: "Lees meer gedetailleerd",
    nav_home: "Tuis",
    nav_my_projects_short: "My Projekte",
    search_skills: "Soek vaardighede...",
    project_status_in_development: "In Ontwikkeling",
    project_status_shelved: "Geskrap",
    project_status_production: "Produksie",
    project_status_improving: "Verbetering",
    project_title_doenit: "Doenit",
    project_desc_doenit: "’n Afrikaanse ToDo-lysprogram wat eenvoudig, privaat en vanlyn-vaardig gebou is.",
    project_title_vinkel_of_koljander: "Vinkel Of Koljander",
    project_desc_vinkel_of_koljander: "’n Webwerf wat ek vir my gesin geskep het om resepte te deel",
    project_title_wedding_website: "My trouwebwerf",
    project_desc_wedding_website:
      "’n Webwerf wat ek vir my troue gebou het sodat gaste kan RSVP, basiese inligting kan vind en die geskenkregister kan hanteer.",
    project_title_tradesmith: "Tradesmith",
    project_desc_tradesmith: "’n Projek om kriptovaluta outomaties te verhandel op grond van ’n stel reëls en strategieë.",
    project_title_console_colours: "Console Kleure",
    project_desc_console_colours: "’n Klein biblioteek om kleur by konsooluitvoer in Node.js te voeg.",
    project_title_woorde_wenk: "Woorde Wenk",
    project_desc_woorde_wenk: "’n Eenvoudige woordspel vir Afrikaansleerlinge om hul woordeskat te oefen.",
    project_title_this_website: "Hierdie Webwerf",
    project_desc_this_website: "My persoonlike webwerf om myself bekend te stel",
    about_introduction: "Inleiding",
    about_summary: "Opsomming",
    about_languages: "Tale",
    about_english: "Engels",
    about_english_level: "Vlot",
    about_afrikaans: "Afrikaans",
    about_afrikaans_level: "Vlot",
    about_german: "Duits",
    about_german_level: "Elementêr (A2)",
    about_date_of_birth: "Geboortedatum",
    about_location: "Ligging",
    about_south_africa: "Suid-Afrika",
    about_south_africa_label: "My huidige woonplek",
    about_luxembourg: "Luxemburg",
    about_luxembourg_label: "Soek werkgeleenthede in Luxemburg",
    about_availability: "Beskikbaarheid",
    about_references: "Verwysings",
    about_available_upon_request: "Beskikbaar op aanvraag",
    about_hobbies: "Stokperdjies",
    about_reading: "Lees",
    about_reading_desc: "Persoonlike ontwikkeling en fiksie",
    about_coding: "Kodering",
    about_coding_desc: "Bou projekte en verken nuwe idees",
    about_exploring: "Verken",
    about_exploring_desc: "Natuur, plekke en vars perspektiewe",
    about_jogging: "Hardloop",
    about_jogging_desc: "Het 2 maratons voltooi",
    about_education: "Onderwys",
    about_university: "Universiteit",
    about_university_desc:
      "Ek het my voorgraadse/baccalaureusstudie in 2020 aan die Universiteit van Stellenbosch voltooi. Ek het in Wiskunde en Rekenaarwetenskap gemajor.",
    about_high_school: "Hoërskool",
    about_high_school_desc: "Ek het my matriek in 2016 in Suid-Afrika, Kaapstad, voltooi.",
    about_other_education: "Ander Onderwys",
    about_other_education_p1:
      "Ek het ’n leierskap- en avontuurprogram in my gapingjaar deur 2017 bygewoon.",
    about_other_education_p2:
      "Ek het ook deur verskeie Udemy-kursusse gegaan. Die meeste van my leer in die laaste paar jaar kom van my persoonlike projekte en selfstudie.",
    about_work_experience: "Werkervaring",
    about_unaffi: "UNAFFI",
    about_unaffi_li_1:
      "Het frontend-argitektuurbesluite gelei, insluitend datamodellering, API-ontwerp, vouerstruktuur en kode-organisasie standaarde.",
    about_unaffi_li_2:
      "Het alle kode-oorsigte in die span gedoen en ESLint-standaarde en beste praktyke toegepas.",
    about_unaffi_li_3: "Het toepassings ontwikkel met JavaScript, SvelteKit, Express, Zod en OpenAPI.",
    about_unaffi_li_4:
      "Het verifikasiestelsels met Ory geïntegreer en mobiele apps (vir web, Android en iOS) gebou met SvelteKit en CapacitorJS.",
    about_unaffi_li_5: "Het outomatiseringsskripte geskep om bedieneroperasies en ontplooiingswerkvloei te stroomlyn.",
    about_unaffi_li_6: "Het saamgewerk met ’n 4-persoon tegniese span op funksie-ontwikkeling en lewering.",
    about_gatekeeper: "Gatekeeper Technologies",
    about_gatekeeper_li_1:
      "Het ’n klein span gelei om 2 nuwe toepassings te skep en 6 bestaande toepassings te onderhou, veral vir die Wes-Kaapse Trafiekdepartement.",
    about_gatekeeper_li_2:
      "Het die volle projeklewensiklus besit, van kliëntvereistes en oplossingontwerp tot implementering, lewering en ondersteuning.",
    about_gatekeeper_li_3:
      "Het kliëntgesentreerde toepassings gebou met die JourneyApps-platform, wat XML, JavaScript en TypeScript gebruik.",
    about_gatekeeper_li_4: "Het verskeie private npm-pakkette vir interne maatskappygebruik gepubliseer.",
    about_gatekeeper_li_5: "Het alle spanlede opgelei terwyl die maatskappy van 3 na 10 ontwikkelaars gegroei het.",
  },
};
